import { BuiltInProviderType } from "next-auth/providers/index";
import { LiteralUnion } from "next-auth/react";

type OAuthTheme = {
  [key in LiteralUnion<BuiltInProviderType>]:
    | {
        logo: string;
        colorCode: string;
      }
    | undefined;
};

export const OAuthTheme: OAuthTheme = {
  line: {
    logo: "/oauth/line.svg",
    colorCode: "#00B900",
  },
  email: undefined,
  oauth: undefined,
  credentials: undefined,
  "42-school": undefined,
  apple: undefined,
  atlassian: undefined,
  auth0: undefined,
  authentik: undefined,
  "azure-ad-b2c": undefined,
  "azure-ad": undefined,
  battlenet: undefined,
  box: undefined,
  "boxyhq-saml": undefined,
  bungie: undefined,
  cognito: undefined,
  coinbase: undefined,
  discord: undefined,
  dropbox: undefined,
  "duende-identity-server6": undefined,
  eveonline: undefined,
  facebook: undefined,
  faceit: undefined,
  foursquare: undefined,
  freshbooks: undefined,
  fusionauth: undefined,
  github: undefined,
  gitlab: undefined,
  google: undefined,
  hubspot: undefined,
  "identity-server4": undefined,
  index: undefined,
  instagram: undefined,
  kakao: undefined,
  keycloak: undefined,
  linkedin: undefined,
  mailchimp: undefined,
  mailru: undefined,
  medium: undefined,
  naver: undefined,
  netlify: undefined,
  "oauth-types": undefined,
  okta: undefined,
  onelogin: undefined,
  osso: undefined,
  osu: undefined,
  passage: undefined,
  patreon: undefined,
  pinterest: undefined,
  pipedrive: undefined,
  reddit: undefined,
  salesforce: undefined,
  slack: undefined,
  spotify: undefined,
  strava: undefined,
  todoist: undefined,
  trakt: undefined,
  twitch: undefined,
  twitter: undefined,
  "united-effects": undefined,
  vk: undefined,
  wikimedia: undefined,
  wordpress: undefined,
  workos: undefined,
  yandex: undefined,
  zitadel: undefined,
  zoho: undefined,
  zoom: undefined,
};
